CREATE TABLE BUDGET(CATEGORY_ID VARCHAR(10) NOT NULL,USER_ID INT,AMOUNT NUMERIC NOT NULL, BUDGET_PLAN VARCHAR(10),
CREATED_DATE DATETIME,MODIFIED_DATE DATETIME)

SELECT * FROM BUDGET

--STORED PROCEDURES--

CREATE PROCEDURE SP_BUDGET(@CATEGORY_ID VARCHAR(10),
@USER_ID VARCHAR(10),
@AMOUNT NUMERIC,
@BUDGET_PLAN VARCHAR(10))
WITH ENCRYPTION
AS

BEGIN
    INSERT INTO BUDGET(CATEGORY_ID,USER_ID,AMOUNT,BUDGET_PLAN,CREATED_DATE,MODIFIED_DATE)
	VALUES(@CATEGORY_ID,@USER_ID ,@AMOUNT ,  @BUDGET_PLAN ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
END
--DROP PROCEDURE[SP-BUDGET]

EXEC SP_BUDGET 111,1,500,'WEEKLY'
EXEC SP_BUDGET 112,2,2000,'MONTHLY'



---READ ALL---
CREATE PROCEDURE SP_BUDGET_READALL
WITH ENCRYPTION
AS
BEGIN
SELECT * FROM BUDGET
END


EXEC SP_BUDGET_READALL